name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install SSH Key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > key.pem
          chmod 600 key.pem

      - name: Add EC2 host to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Clean up EC2 directory before copying files
        run: |
          ssh -i key.pem -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            find ${{ secrets.EC2_APP_DIR }} -mindepth 1 ! -name 'service-file' -exec rm -rf {} +
          EOF

      - name: Sync backend files to EC2 using rsync
        run: |
          echo "node_modules/" > rsync-exclude.txt
          echo ".env" >> rsync-exclude.txt
          rsync -avz --delete --filter "P service-file/" --exclude-from=rsync-exclude.txt -e "ssh -i key.pem -o StrictHostKeyChecking=no" ./saharasprout-backend/ ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:${{ secrets.EC2_APP_DIR }}

      - name: Debug EC2 files
        run: |
          ssh -i key.pem -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            ls -la ${{ secrets.EC2_APP_DIR }}
          EOF

      - name: Restart application
        run: |
          ssh -i key.pem -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd ${{ secrets.EC2_APP_DIR }}
            npm install
            pm2 reload index.js --name "saharasprout-backend" || pm2 start index.js --name "saharasprout-backend"
          EOF
