name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code # Checks out the repository
        uses: actions/checkout@v3 # Updated to v3 for Node 20 compatibility

      - name: Debug Environment Variables # Optional debugging
        run: |
          echo "EC2_HOST: ${{ secrets.EC2_HOST }}"
          echo "EC2_USER: ${{ secrets.EC2_USER }}"
          echo "EC2_APP_DIR: ${{ secrets.EC2_APP_DIR }}"
          echo "KEY length: ${#EC2_KEY}"

      - name: Install SSH Key # Set up SSH key for secure access
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > key.pem
          chmod 400 key.pem

      - name: Create .ssh directory and add EC2 host to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy application to EC2 # Copy files over to EC2
        run: |
          scp -i key.pem -o StrictHostKeyChecking=no -r ./* ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:${{ secrets.EC2_APP_DIR }}

      - name: SSH to EC2 and restart app # Restart app on EC2 server
        run: |
          ssh -i key.pem -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd ${{ secrets.EC2_APP_DIR }}
            npm install
            pm2 restart all || pm2 start index.js --name "saharasprout-backend"
          EOF
